# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The BIRO Lab
email: hao.su@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are developing both enabling technologies (i.e. high torque density motors and soft fabric sensors) and robotic systems to augment human capability with wearable robots. Soft exoskeleton is a new design methodology that optimizes both comfort and performance of the users. We believe that our lightweight and compliant exoskeleton will be new intervention and rehabilitation solutions for both neurological and musculoskeletal disorders, e.g. osteoarthritis and children with cerebral palsy.
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages
  - _productPages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


navigation:
  - text: Home
    url: /home
  - text: Products
    url: /products